---
- hosts : all
  become : yes
  gather_facts : yes
  tasks :
  - name : Install webserver on node side
    apt :
      name : apache2
      state : present

  - name : start webserver on debian node side
    service :
       name : apache2
       state : started